### ISSUE TITLE
Setup workflow for processing data

### ISSUE THREAD

**Issue by mhebing** [ddionrails/soep-test#2]
- [x] script to clean the raw data: raw --> clean
- [x] based on clean, generate the long data: clean --> long
- [x] generate additional variables (e.g., BMI), based on long: long --> gen

Fore each of these steps, use our directory layout:

* input
* script
* output
* main.do (project-specifc)

main.do (for all projects):

1. run raw --> clean
2. copy output to next input
3. …

**Comment by mhebing** [comment]
https://github.com/ddionrails/testdata

**Comment by mpahl** [comment]
Would it be good to create a new folder (data) to put in raw, cleaning and long? 
Otherwise the folder structure gets very unclear, isn't it?

**Comment by mhebing** [comment]
Sounds good!
